"""cria tabela historico_comportamento

Revision ID: 684700e82b27
Revises: 8d2ec4066387
Create Date: 2025-12-20 11:56:23.699290+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '684700e82b27'
down_revision: Union[str, None] = '8d2ec4066387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico_comportamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('emprestimo_id', sa.Integer(), nullable=False),
    sa.Column('devolvido_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estava_atrasado', sa.Boolean(), nullable=False),
    sa.Column('dias_atraso', sa.Integer(), nullable=False),
    sa.Column('multa_gerada', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['emprestimo_id'], ['emprestimos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_comportamento_emprestimo_id'), 'historico_comportamento', ['emprestimo_id'], unique=False)
    op.create_index(op.f('ix_historico_comportamento_id'), 'historico_comportamento', ['id'], unique=False)
    op.create_index(op.f('ix_historico_comportamento_usuario_id'), 'historico_comportamento', ['usuario_id'], unique=False)
    op.alter_column('usuarios', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('usuarios', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.alter_column('usuarios', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('usuarios', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_historico_comportamento_usuario_id'), table_name='historico_comportamento')
    op.drop_index(op.f('ix_historico_comportamento_id'), table_name='historico_comportamento')
    op.drop_index(op.f('ix_historico_comportamento_emprestimo_id'), table_name='historico_comportamento')
    op.drop_table('historico_comportamento')
    # ### end Alembic commands ###
