"""Initial schema

Revision ID: 6b611d2dfc85
Revises: 
Create Date: 2025-12-21 15:40:11.753272+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b611d2dfc85'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('autor', sa.String(length=255), nullable=True),
    sa.Column('isbn', sa.String(length=32), nullable=True),
    sa.Column('quantidade_total', sa.Integer(), nullable=False),
    sa.Column('quantidade_disponivel', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantidade_disponivel >= 0', name='chk_livro_quantidade_disponivel_nonneg'),
    sa.CheckConstraint('quantidade_total >= 0', name='chk_livro_quantidade_total_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_livro_titulo_autor', 'livros', ['titulo', 'autor'], unique=False)
    op.create_index(op.f('ix_livros_area'), 'livros', ['area'], unique=False)
    op.create_index(op.f('ix_livros_isbn'), 'livros', ['isbn'], unique=True)
    op.create_index(op.f('ix_livros_titulo'), 'livros', ['titulo'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('aluno', 'bibliotecario', 'admin', name='usuariorole'), server_default='aluno', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usuario_nome_email', 'usuarios', ['nome', 'email'], unique=False)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_nome'), 'usuarios', ['nome'], unique=False)
    op.create_table('emprestimos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('livro_id', sa.Integer(), nullable=False),
    sa.Column('data_emprestimo', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_prevista_devolucao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_devolucao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('renovacoes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ativo', 'devolvido', 'atrasado', name='emprestimostatus'), server_default='ativo', nullable=False),
    sa.ForeignKeyConstraint(['livro_id'], ['livros.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'livro_id', 'status', name='uq_usuario_livro_status')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('livro_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('posicao', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ativa', 'atendida', 'cancelada', name='reservastatus'), server_default='ativa', nullable=False),
    sa.ForeignKeyConstraint(['livro_id'], ['livros.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_comportamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('emprestimo_id', sa.Integer(), nullable=False),
    sa.Column('devolvido_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estava_atrasado', sa.Boolean(), nullable=False),
    sa.Column('dias_atraso', sa.Integer(), nullable=False),
    sa.Column('multa_gerada', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['emprestimo_id'], ['emprestimos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_comportamento_emprestimo_id'), 'historico_comportamento', ['emprestimo_id'], unique=False)
    op.create_index(op.f('ix_historico_comportamento_id'), 'historico_comportamento', ['id'], unique=False)
    op.create_index(op.f('ix_historico_comportamento_usuario_id'), 'historico_comportamento', ['usuario_id'], unique=False)
    op.create_table('multas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emprestimo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'paga', 'cancelada', name='multastatus'), server_default='pendente', nullable=False),
    sa.Column('gerada_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('paga_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emprestimo_id'], ['emprestimos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multas')
    op.drop_index(op.f('ix_historico_comportamento_usuario_id'), table_name='historico_comportamento')
    op.drop_index(op.f('ix_historico_comportamento_id'), table_name='historico_comportamento')
    op.drop_index(op.f('ix_historico_comportamento_emprestimo_id'), table_name='historico_comportamento')
    op.drop_table('historico_comportamento')
    op.drop_table('reservas')
    op.drop_table('emprestimos')
    op.drop_index(op.f('ix_usuarios_nome'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index('ix_usuario_nome_email', table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_livros_titulo'), table_name='livros')
    op.drop_index(op.f('ix_livros_isbn'), table_name='livros')
    op.drop_index(op.f('ix_livros_area'), table_name='livros')
    op.drop_index('ix_livro_titulo_autor', table_name='livros')
    op.drop_table('livros')
    # ### end Alembic commands ###
