"""Remove campos de multa do historico_comportamento

Revision ID: c7c0715e2f94
Revises: b5308887cb04
Create Date: 2025-12-20 18:01:55.004058+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7c0715e2f94'
down_revision: Union[str, None] = 'b5308887cb04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('historico_comportamento', 'emprestimo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('historico_comportamento', 'devolvido_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('historico_comportamento', 'estava_atrasado',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('historico_comportamento', 'dias_atraso',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('historico_comportamento', 'multa_gerada',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_index(op.f('ix_historico_comportamento_multa_id'), table_name='historico_comportamento')
    op.drop_constraint(op.f('historico_comportamento_multa_id_fkey'), 'historico_comportamento', type_='foreignkey')
    op.drop_column('historico_comportamento', 'multa_id')
    op.drop_column('historico_comportamento', 'valor_pago')
    op.drop_column('historico_comportamento', 'pago_em')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historico_comportamento', sa.Column('pago_em', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('historico_comportamento', sa.Column('valor_pago', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('historico_comportamento', sa.Column('multa_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('historico_comportamento_multa_id_fkey'), 'historico_comportamento', 'multas', ['multa_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_historico_comportamento_multa_id'), 'historico_comportamento', ['multa_id'], unique=False)
    op.alter_column('historico_comportamento', 'multa_gerada',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('historico_comportamento', 'dias_atraso',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('historico_comportamento', 'estava_atrasado',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('historico_comportamento', 'devolvido_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('historico_comportamento', 'emprestimo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
